// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChooseArea: typeof import('./src/components/chooseArea/index.vue')['default']
    CustomHeader: typeof import('./src/components/Header/CustomHeader.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    IconList: typeof import('./src/components/Icon/IconList.vue')['default']
    IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MenuItem: typeof import('./src/components/Menu/MenuItem.vue')['default']
    MessageList: typeof import('./src/components/List/MessageList.vue')['default']
    NoticePad: typeof import('./src/components/NoticePad/index.vue')['default']
    Notification: typeof import('./src/components/NoticePad/Notification.vue')['default']
    Src: typeof import('./src/components/NoticePad/src/index.vue')['default']
    SubMenu: typeof import('./src/components/Menu/SubMenu.vue')['default']
    Trend: typeof import('./src/components/Trend/index.vue')['default']
  }
}

export { }
