// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasicForm: typeof import('./src/components/Form/BasicForm.vue')['default']
    ChooseArea: typeof import('./src/components/chooseArea/index.vue')['default']
    ChooseCity: typeof import('./src/components/ChooseCity/index.vue')['default']
    CityList: typeof import('./src/components/ChooseCity/CityList.vue')['default']
    CustomHeader: typeof import('./src/components/Header/CustomHeader.vue')['default']
    Descriptions: typeof import('./src/components/Descriptions/index.vue')['default']
    DProgress: typeof import('./src/components/DProgress/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FormItem: typeof import('./src/components/Form/FormItem.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    IconList: typeof import('./src/components/Icon/IconList.vue')['default']
    IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MenuItem: typeof import('./src/components/Menu/MenuItem.vue')['default']
    MessageList: typeof import('./src/components/List/MessageList.vue')['default']
    NoticePad: typeof import('./src/components/NoticePad/index.vue')['default']
    Notification: typeof import('./src/components/NoticePad/Notification.vue')['default']
    SubMenu: typeof import('./src/components/Menu/SubMenu.vue')['default']
    Trend: typeof import('./src/components/Trend/index.vue')['default']
  }
}

export {}
